# [START app_yaml]
runtime: nodejs
env: flex

# [START env]
env_variables:
  SQL_USER: 'postgres'
  SQL_PASSWORD: 'postgres'
  SQL_DATABASE: 'direktoribisnis'
  # e.g. my-awesome-project:us-central1:my-cloud-sql-instance
  INSTANCE_CONNECTION_NAME: 'dirbis-414d9:us-central1:direktoribisnis'
# [END env]

# [START cloudsql_settings]
beta_settings:
  # The connection name of your instance, available by using
  # 'gcloud beta sql instances describe [INSTANCE_NAME]' or from
  # the Instance details page in the Google Cloud Platform Console.
  cloud_sql_instances: 'dirbis-414d9:us-central1:direktoribisnis'
# [END cloudsql_settings]
# [END app_yaml]